server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

Jieba:
  useHMM: true
  dictPath: ""

redis:
  TextRecord:
    address: 1.1.1.1
    db: 1
  IndexRecord:
    address: 1.1.1.1
    db: 2
